version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "asteroid-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1xc4hpqzjwa4a"
s3_prefix = "asteroid-app"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"

